# Generated by Django 5.2.8 on 2026-09-27 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serviteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eglise_nom', models.CharField(default='Église Nouvel Apostolat Authentique en RDC', max_length=200, verbose_name='Église')),
                ('region_apostolique', models.CharField(blank=True, max_length=150, verbose_name='Région Apostolique')),
                ('district_apostolique', models.CharField(blank=True, max_length=150, verbose_name='District Apostolique de')),
                ('district_ancien', models.CharField(blank=True, max_length=150, verbose_name="District d'Ancien de")),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('post_nom', models.CharField(blank=True, max_length=100, verbose_name='Post nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('lieu_naissance', models.CharField(blank=True, max_length=150, verbose_name='Lieu de naissance')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('etat_civil', models.CharField(blank=True, choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf/Veuve'), ('union_libre', 'En union libre')], max_length=30, verbose_name='État civil')),
                ('telephone', models.CharField(max_length=30, verbose_name='Téléphone (WhatsApp)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Photo')),
                ('baptise_eau_date', models.DateField(blank=True, null=True, verbose_name="Date de baptême d'eau")),
                ('baptise_eau_par', models.CharField(blank=True, max_length=200, verbose_name="Personne ayant effectué le baptême d'eau")),
                ('saint_sceau_date', models.DateField(blank=True, null=True, verbose_name='Date de Saint Scellé')),
                ('saint_sceau_par', models.CharField(blank=True, max_length=200, verbose_name='Personne ayant effectué le Saint Scellé')),
                ('communaute_origine', models.CharField(blank=True, max_length=150, verbose_name="Communauté d'origine")),
                ('date_ordination', models.DateField(blank=True, null=True, verbose_name="Date d'ordination actuelle")),
                ('ministere', models.CharField(blank=True, max_length=150, verbose_name='Ministère')),
                ('ordination_par', models.CharField(blank=True, max_length=200, verbose_name="Personne ayant effectué l'ordination")),
                ('champ_apostolique', models.CharField(blank=True, max_length=150, verbose_name='Champ Apostolique Affecté')),
                ('niveau_etudes', models.CharField(blank=True, max_length=120, verbose_name='Niveau')),
                ('domaine_etudes', models.CharField(blank=True, max_length=150, verbose_name='Domaine')),
                ('disponibilite', models.CharField(choices=[('temps_plein', 'Temps plein'), ('partielle', 'Partielle'), ('indisponible', 'Indisponible')], default='temps_plein', max_length=30, verbose_name="Disponibilité à l'œuvre")),
                ('lieu_remplissage', models.CharField(blank=True, max_length=150, verbose_name='Lieu de remplissage')),
                ('date_remplissage', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('signature', models.CharField(blank=True, max_length=200, verbose_name='Signature')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Serviteur de Dieu',
                'verbose_name_plural': 'Serviteurs de Dieu',
                'ordering': ['nom', 'post_nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumMinisteriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=1, verbose_name='Ordre')),
                ('annee', models.CharField(blank=True, max_length=10, verbose_name='Année')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('details', models.CharField(blank=True, max_length=255, verbose_name='Détails')),
                ('serviteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='serviteurs.serviteur', verbose_name='Serviteur')),
            ],
            options={
                'verbose_name': 'Parcours ministériel',
                'verbose_name_plural': 'Parcours ministériels',
                'ordering': ['ordre'],
            },
        ),
    ]
