# Generated by Django 6.1.1 on 2026-10-02 22:12

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviteurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviteur',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom de famille'),
        ),
        migrations.AddConstraint(
            model_name='serviteur',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email', ''), _negated=True), name='serviteur_email_unique_ci'),
        ),
        migrations.AddConstraint(
            model_name='serviteur',
            constraint=models.UniqueConstraint(fields=('telephone',), name='serviteur_telephone_unique'),
        ),
        migrations.AddConstraint(
            model_name='serviteur',
            constraint=models.UniqueConstraint(fields=('nom', 'post_nom', 'prenom', 'date_naissance'), name='serviteur_identite_unique'),
        ),
    ]
