# Generated by Django 6.1.1 on 2026-10-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviteurs', '0002_alter_serviteur_nom_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculumministeriel',
            options={'ordering': ['-annee', 'ordre'], 'verbose_name': 'Parcours ministériel', 'verbose_name_plural': 'Parcours ministériels'},
        ),
        migrations.AddField(
            model_name='serviteur',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse'),
        ),
    ]
